optimization: update User and System pages
WeOps-Lab/rewind-web pull request #1
Opened 2024-11-22 10:27 UTC by chenlinggg

2024-11-22 11:06 UTC, etherfurnace requested changes

2024-11-22 11:06 UTC, etherfurnace commented on src/app/system-manager/constants/menu.ts
> +      icon: 'jiqiren2',
选择合适的图标

2024-11-22 11:06 UTC, etherfurnace commented on src/app/system-manager/locales/en.json
> +    "menu": "Knowledge345"
menu 不对

2024-11-22 11:06 UTC, etherfurnace commented on src/app/system-manager/locales/zh.json
> +    "menu": "知识库"
i18n 配置不正确，检查

2024-11-25 02:07 UTC, CharlesWhj commented on package.json
>      "antd": "^5.21.5",
package.json不要提上来，除非是框架公共的插件

2024-11-25 02:07 UTC, CharlesWhj commented on src/app/system-manager/api/data/route.ts
空文件不用提

2024-11-25 02:07 UTC, CharlesWhj commented on src/app/system-manager/teamspage/page.tsx
> +          {!key.children || key.children.length === 0 ? (
删除的组件用message

2024-11-25 02:33 UTC, chenlinggg commented on src/app/system-manager/teamspage/page.tsx
> +          {!key.children || key.children.length === 0 ? (
message.success('Delete team success');

2024-11-25 02:33 UTC, CharlesWhj commented
收到，谢谢。

2024-11-25 02:34 UTC, chenlinggg commented on src/app/system-manager/api/data/route.ts
好的

2024-11-25 02:38 UTC, chenlinggg commented on package.json
>      "antd": "^5.21.5",
<img width="163" alt="github上传的忽略" src="https://github.com/user-attachments/assets/a4201c35-469e-4843-b756-7603e6e0e25c">
老师，我添加了package.json，应该不会再删除该文件了

2024-11-25 03:01 UTC, chenlinggg commented on src/app/system-manager/locales/zh.json
> +    "menu": "知识库"
![Uploading zh.png…]()

2024-11-25 03:01 UTC, chenlinggg commented on src/app/system-manager/locales/en.json
> +    "menu": "Knowledge345"
![Uploading en.png…]()

2024-11-25 03:03 UTC, chenlinggg commented on src/app/system-manager/locales/zh.json
> +    "menu": "知识库"
<img width="240" alt="zh" src="https://github.com/user-attachments/assets/90fcaf70-3a16-4b4e-8eb9-1691ce81ca0d">

2024-11-25 03:05 UTC, chenlinggg commented on src/app/system-manager/locales/en.json
> +    "menu": "Knowledge345"
<img width="303" alt="en" src="https://github.com/user-attachments/assets/23ad9bb4-70f3-4620-997e-168116830d4f">

2024-11-25 03:23 UTC, chenlinggg commented on src/app/system-manager/constants/menu.ts
> +      icon: 'jiqiren2',
<img width="282" alt="图标的选取" src="https://github.com/user-attachments/assets/1d74dd6c-e39b-4bde-b463-d8da45be6040">

2024-11-25 05:51 UTC, closed without merging